name: loadbalancer-projrct 

trigger:
- main
- feature/anu**

pool: devops-pool

parameters:
  - name: environment
    displayName: Select environment
    type: string
    default: dev
    values:
      - dev
      - test
      - prod

  - name: runscanning
    displayName: Run scanning job
    type: string
    default: "true"
    values:
      - "true"
      - "false"

stages:
  - stage: terraforbuildstage
    jobs:
      - job: 
        displayName: terraform build
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'terraform-infra'
            backendAzureRmStorageAccountName: 'stgannu2112'
            backendAzureRmContainerName: 'stgannu2112'
            backendAzureRmKey: 'dev.terraform.tfstate'
        
        - task: TerraformTask@5
          displayName: Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        - task: CmdLine@2
          displayName: fmt
          inputs:
            script: 'fmt'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'

        - task: TerraformTask@5
          displayName: Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'terraform-infra'

  - stage: terraformcodescanning
    jobs:
      - job: tflinttfsec
        displayName: terraform testing job
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              tflint
              # tfsec
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
        

