trigger: 
- main
- feature/*
pool: devops-pool
stages:
  - stage: testingstage
    jobs:
      - job: tflinttfsec
        displayName: terraform testing job
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'terraform-infra'
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
              tflint
               tfsec
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
  - stage: buildstage
    jobs:
      - job: 
        displayName: terraform build
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'terraform-infra'
            backendAzureRmStorageAccountName: 'stgannu2112'
            backendAzureRmContainerName: 'stgannu2112'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          displayName: terraform validat
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'terraform-infra'
  - stage: validationstage
    jobs:
      - job: 
        displayName: manualvalidation
        steps:
        - task: ManualValidation@1
          timeoutInMinutes: 40
          inputs:
            notifyUsers: 'devopsannu@gmail.com'
            instructions: please review the code and approve

    pool: server
    condition: succeeded()
    dependsOn: buildstage
        